### ISSUE TITLE
这个项目怎么运行起来？

### ISSUE THREAD

**Issue by VolleyballBIA** [wcwu/NettyChat#1]
已经按照Maven项目导入Eclipse中，但是不知道怎么运行？有时间写个简单启动步骤更新一下吧，谢谢。

**Comment by tingwhere** [comment]
Same question for me. I deploy it in Eclipse Mar3.1. But fail to run it.
The warning messages in console are below:
now send msg: 
Exception in thread "main" java.lang.NullPointerException
	at server.ServerUI.addSendMessageListener(ServerUI.java:49)
	at server.ServerUI.<init>(ServerUI.java:45)
	at server.ServerUI.main(ServerUI.java:27).
